"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// style sheets
import "./globals.css";
import "@radix-ui/themes/styles.css";

// urban memories
import { UMIDBClientWrapper } from "@/Contexts/UMIndexedDB/UMIDBClientWrapper";
import { UMIndexedDBConfig } from "@/Contexts/UMIndexedDB/config";
import { ItemsWrapper } from "@/Contexts/ItemsContext/ItemsWrapper";
import { AppWrapper } from "@/Components/AppComponents/AppWrapper/AppWrapper";

const inter = Inter({ subsets: ["latin"] });

// ----- temp disabled because layout is client component for now ------
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="manifest"
          href="/manifest.json"
          crossOrigin="use-credentials"
        />
        <link rel="apple-touch-icon" href="/images/apple-touch-icon.png" />
        <link rel="icon" href="/images/favicon.ico" />
        <meta name="theme-color" content="#E19C3E" />
      </head>
      <body>
        <UMIDBClientWrapper {...UMIndexedDBConfig}>
          <ItemsWrapper>
            <AppWrapper>{children}</AppWrapper>
          </ItemsWrapper>
        </UMIDBClientWrapper>
      </body>
    </html>
  );
}
